```{r}
insurance <- read.csv("D:/Academic Data/Trimester 3/EDA/Practise/insurance.csv", stringsAsFactors = TRUE)
str(insurance)
```
```{r}
summary(insurance$charges)
```
```{r}
hist(insurance$charges)
```
```{r}
table(insurance$sex)
table(insurance$smoker)
table(insurance$region)
```
```{r}
cor(insurance[c("age", "bmi", "children", "charges")])
```
```{r}
plot(insurance[c("age", "bmi", "children", "charges")])
```
```{r}
library("psych")
pairs.panels(insurance[c("age", "bmi", "children", "charges")])
```
```{r}
ins_model <- lm(charges ~ ., data = insurance)
ins_model
```
```{r}
summary(ins_model)
#The residuals section provides summary statistics for the errors in our predictions
#P-values will define the significance of the variables
#Coefficient of determination. Closer to 1 is better.
```
```{r}
#Introducing non-linear variables to increase the performance of the model
#Introducing categorical variables to increase the performance of the model
insurance$age2 <- insurance$age^2
insurance$bmi30 <- ifelse(insurance$bmi >= 30,1,0)
```
```{r}
#Adding interactions between variables.
ins_model2 <- lm(charges ~ age + age2 + children + bmi + sex + bmi30*smoker +
                   region, data = insurance)
summary(ins_model2)
```

